name: "Terraform setup and apply"
description: "Applys a terraform plan file from an artifact"
inputs:
  terraform_directory: 
    description: 'where to execute terraform'
    required: true
  terraform_version: 
    description: 'GCP Terraform Version'
    required: true
    default: 1.2.9
  github_token: 
    description: 'github secret'
    required: true
  run_id:
    description: 'Run ID of the plan workflow'
    required: true
  pr_id:
    description: 'Pull request ID'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        terraform init

    - name: Download Plan
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.pr_id }}-tf-plan
        run-id: ${{ inputs.run_id }}
        path: ${{ inputs.terraform_directory }}
        github-token: ${{ inputs.github_token }}

    - name: Terraform Apply
      id: apply
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        echo 'apply<<EOF' >> $GITHUB_OUTPUT
        terraform apply -input=false -no-color tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Comment Apply
      id: comment-apply
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_id }}
        body: |
          Terraform Apply:

          ```
          ${{ steps.apply.outputs.apply }}
          ```