name: Terraform Apply

on:
  pull_request:
    types: [closed]

env:
  TERRAFORM_VERSION: "1.9.8"
  TF_IN_AUTOMATION: "True"

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - name: Get PR ID
        id: pr-id
        run: echo "PR_ID=$(jq .pull_request.number $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Get run ID of "Plan" workflow
        id: get-run-id
        run: |
          OTHER_REPO="${{ github.repository }}"
          WF_NAME="Terraform Plan"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow "${WF_NAME}" --json databaseId --jq .[0].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Terraform Apply
        uses: ./.github/apply
        with:
          terraform_directory: "terraform"
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          github_token: ${{ secrets.GH_TOKEN }}
          run_id: ${{ steps.get-run-id.outputs.RUN_ID }}
          pr_id: ${{ env.PR_ID }}